Directly configure the rust toolchain for CI (#1087)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,13 +32,19 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Configure rust version
+        id: rust-version
+        run: |
+          VERSION=$(cat ../rust-toolchain.toml| sed -rn 's/^channel = "([0-9]+\.[0-9]+\.[0-9]+)"/\1/p')
+          if [ -z "${VERSION}" ]; then
+            echo "Version not found in rust-toolchain.toml"
+            exit 1
+          fi
+          echo VERSION=$VERSION >> "$GITHUB_OUTPUT"
       - name: Setup Rust
         uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # master
         with:
-          toolchain: stable
-      - name: Add Rust toolchain components
-        run: |
-          rustup component add rustfmt clippy
+          toolchain: ${{ steps.rust-version.outputs.VERSION }}
       - name: Rust build cache
         uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
         with:
